// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file hermes/object.proto (package hermes, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file hermes/object.proto.
 */
export const file_hermes_object: GenFile = /*@__PURE__*/
  fileDesc("ChNoZXJtZXMvb2JqZWN0LnByb3RvEgZoZXJtZXMiggIKBFVzZXISCgoCaWQYASABKAkSEAoIYXV0aDBfaWQYAiABKAkSDQoFZW1haWwYAyABKAkSDAoEbmFtZRgEIAEoCRIZChFzdWJzY3JpcHRpb25fdGllchgFIAEoCRIuCgpjcmVhdGVkX2F0GAYgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GAcgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIxCg1sYXN0X2xvZ2luX2F0GAggASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIRCglpc19hY3RpdmUYCSABKAhCEloQaGVybWVzL2FwaS9wcm90b2IGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message hermes.User
 */
export type User = Message<"hermes.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string auth0_id = 2;
   */
  auth0Id: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: string name = 4;
   */
  name: string;

  /**
   * @generated from field: string subscription_tier = 5;
   */
  subscriptionTier: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 7;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp last_login_at = 8;
   */
  lastLoginAt?: Timestamp;

  /**
   * @generated from field: bool is_active = 9;
   */
  isActive: boolean;
};

/**
 * Describes the message hermes.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_hermes_object, 0);

