// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file janus/gateway.proto (package janus, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file janus/gateway.proto.
 */
export const file_janus_gateway: GenFile = /*@__PURE__*/
  fileDesc("ChNqYW51cy9nYXRld2F5LnByb3RvEgVqYW51czIQCg5HYXRld2F5U2VydmljZUITWhFnYXRld2F5L2FwaS9wcm90b2IGcHJvdG8z");

/**
 * @generated from service janus.GatewayService
 */
export const GatewayService: GenService<{
}> = /*@__PURE__*/
  serviceDesc(file_janus_gateway, 0);

